package services;

import entities.CategorieProduit;
import entities.Client;
import entities.Commande;
import entities.Employe;
import entities.InterfaceAccueil;
import entities.LigneCommande;
import entities.Menu;
import entities.Poste;
import entities.Produit;
import entities.SousCategorie;
import entities.Statut;
import entities.TVA;
import entities.Tabla;
import entities.TypeCuisson;
import entities.TypeReglement;
import java.util.Date;
import javax.ejb.Singleton;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;

@Singleton
public class jeuDeDonnees implements jeuDeDonneesLocal {

    @PersistenceContext(unitName = "restaurantEE-ejbPU")
    private EntityManager em;
    private boolean etat;

    public jeuDeDonnees() {
        this.etat = false;
    }

    @Override
    public void insererJeuEssai() {
        if (!etat) {
            insererJeuEssai1();
            etat = true;
        }
    }

    private void insererJeuEssai1() {
        // 1: code interface
        // 2: categorie produit
        // 3: sousCategorie produit
        // 4: TVA
        // 5: Statut
        // 6: Produit
        // 7: CategorieMenu
        // 8: Poste
        // 9: Employe
        // 10: Menu
        // 11: Tabla
        // 12: Ligne Commande
        // 13: Commande 
        // 14: type Reglement
        // 15: TypeCuisson
        // 16: Client
        // 17:  
        // 18:  
        // 19:  

        // 1: code interface
        InterfaceAccueil ia01 = new InterfaceAccueil("cuisine", "0000");
        InterfaceAccueil ia02 = new InterfaceAccueil("client", "1111");
        InterfaceAccueil ia03 = new InterfaceAccueil("serveur", "2222");
        InterfaceAccueil ia04 = new InterfaceAccueil("caisse", "3333");

        em.persist(ia01);
        em.persist(ia02);
        em.persist(ia03);
        em.persist(ia04);

        // 2: categorie produit
        CategorieProduit CategorieProduit1 = new CategorieProduit(1, "Entrée");
        CategorieProduit CategorieProduit2 = new CategorieProduit(2, "Plat principal");
        CategorieProduit CategorieProduit3 = new CategorieProduit(3, "Dessert");
        CategorieProduit CategorieProduit4 = new CategorieProduit(8, "Accompagnement");
        CategorieProduit CategorieProduit5 = new CategorieProduit(5, "Sauce");
        CategorieProduit CategorieProduit6 = new CategorieProduit(4, "Boisson");
        CategorieProduit CategorieProduit7 = new CategorieProduit(6, "Amusegueule");
        CategorieProduit CategorieProduit8 = new CategorieProduit(7, "Confiserie");

        // 3: sousCategorie produit
        SousCategorie SousCategorie1 = new SousCategorie("Soupe");
        SousCategorie SousCategorie2 = new SousCategorie("Paella");
        SousCategorie SousCategorie3 = new SousCategorie("Bruschetta");
        SousCategorie SousCategorie4 = new SousCategorie("Crème");
        SousCategorie SousCategorie5 = new SousCategorie("Salade");
        SousCategorie SousCategorie6 = new SousCategorie("Carpaccio");
        SousCategorie SousCategorie7 = new SousCategorie("Jardinière");
        SousCategorie SousCategorie8 = new SousCategorie("Tartare");
        SousCategorie SousCategorie9 = new SousCategorie("Fondant");
        SousCategorie SousCategorie10 = new SousCategorie("Guacamole");
        SousCategorie SousCategorie11 = new SousCategorie("Melon");
        SousCategorie SousCategorie12 = new SousCategorie("Filet");
        SousCategorie SousCategorie13 = new SousCategorie("Charlotte");
        SousCategorie SousCategorie14 = new SousCategorie("L'antioxydant");
        SousCategorie SousCategorie15 = new SousCategorie("Tarte");
        SousCategorie SousCategorie16 = new SousCategorie("Poulet");
        SousCategorie SousCategorie17 = new SousCategorie("Clafoutis");
        SousCategorie SousCategorie18 = new SousCategorie("Moules");
        SousCategorie SousCategorie19 = new SousCategorie("Fleurs");
        SousCategorie SousCategorie20 = new SousCategorie("spaghettis");
        SousCategorie SousCategorie21 = new SousCategorie("Lapin");
        SousCategorie SousCategorie23 = new SousCategorie("Aiguillettes");
        SousCategorie SousCategorie24 = new SousCategorie("Lasagnes");
        SousCategorie SousCategorie25 = new SousCategorie("Fagots");
        SousCategorie SousCategorie26 = new SousCategorie("Financiers");
        SousCategorie SousCategorie27 = new SousCategorie("Cromesqui");
        SousCategorie SousCategorie28 = new SousCategorie("Roulé");
        SousCategorie SousCategorie29 = new SousCategorie("Wok");
        SousCategorie SousCategorie30 = new SousCategorie("Omelette");
        SousCategorie SousCategorie31 = new SousCategorie("Chouquettes");
        SousCategorie SousCategorie32 = new SousCategorie("Granola");
        SousCategorie SousCategorie33 = new SousCategorie("Tartine");
        SousCategorie SousCategorie34 = new SousCategorie("Tian");
        SousCategorie SousCategorie35 = new SousCategorie("Nuggets");
        SousCategorie SousCategorie36 = new SousCategorie("Brioche");
        SousCategorie SousCategorie37 = new SousCategorie("Smoothie");
        SousCategorie SousCategorie38 = new SousCategorie("Aubergines");
        SousCategorie SousCategorie39 = new SousCategorie("Croq'");
        SousCategorie SousCategorie40 = new SousCategorie("Beignets");
        SousCategorie SousCategorie41 = new SousCategorie("Crumble");
        SousCategorie SousCategorie42 = new SousCategorie("Bouchées");
        SousCategorie SousCategorie43 = new SousCategorie("Soufflés");
        SousCategorie SousCategorie44 = new SousCategorie("Pizza");
        SousCategorie SousCategorie45 = new SousCategorie("Bagel");
        SousCategorie SousCategorie46 = new SousCategorie("Cake");
        SousCategorie SousCategorie47 = new SousCategorie("One");
        SousCategorie SousCategorie48 = new SousCategorie("Bowl");
        SousCategorie SousCategorie49 = new SousCategorie("Brochette");
        SousCategorie SousCategorie50 = new SousCategorie("Risotto");
        SousCategorie SousCategorie51 = new SousCategorie("Rouleau");
        SousCategorie SousCategorie52 = new SousCategorie("Velouté");
        SousCategorie SousCategorie53 = new SousCategorie("canard");
        SousCategorie SousCategorie54 = new SousCategorie("Poke");
        SousCategorie SousCategorie55 = new SousCategorie("Tartelettes");
        SousCategorie SousCategorie56 = new SousCategorie("Booster");
        SousCategorie SousCategorie57 = new SousCategorie("Boulettes");
        SousCategorie SousCategorie58 = new SousCategorie("Cordon");
        SousCategorie SousCategorie59 = new SousCategorie("Barres");
        SousCategorie SousCategorie60 = new SousCategorie("Oeuf");
        SousCategorie SousCategorie61 = new SousCategorie("Agneau");
        SousCategorie SousCategorie62 = new SousCategorie("Riz");
        SousCategorie SousCategorie63 = new SousCategorie("Gâteau");
        SousCategorie SousCategorie64 = new SousCategorie("Sablé");
        SousCategorie SousCategorie65 = new SousCategorie("Pâté");
        SousCategorie SousCategorie66 = new SousCategorie("Gigot");
        SousCategorie SousCategorie67 = new SousCategorie("boeuf");
        SousCategorie SousCategorie68 = new SousCategorie("Dessert");
        SousCategorie SousCategorie69 = new SousCategorie("Saucisses");
        SousCategorie SousCategorie70 = new SousCategorie("Blanquette");
        SousCategorie SousCategorie71 = new SousCategorie("Crottes");
        SousCategorie SousCategorie72 = new SousCategorie("Millefeuille");
        SousCategorie SousCategorie73 = new SousCategorie("Popcorn");
        SousCategorie SousCategorie74 = new SousCategorie("Roses");
        SousCategorie SousCategorie75 = new SousCategorie("Gaufre");
        SousCategorie SousCategorie76 = new SousCategorie("Gressins");
        SousCategorie SousCategorie77 = new SousCategorie("Gratin");
        SousCategorie SousCategorie78 = new SousCategorie("Pancakes");
        SousCategorie SousCategorie79 = new SousCategorie("Bouchée");
        SousCategorie SousCategorie80 = new SousCategorie("Maple");
        SousCategorie SousCategorie81 = new SousCategorie("Purée");
        SousCategorie SousCategorie82 = new SousCategorie("Iles");
        SousCategorie SousCategorie83 = new SousCategorie("Douceur");
        SousCategorie SousCategorie84 = new SousCategorie("Camembert");
        SousCategorie SousCategorie85 = new SousCategorie("Pad");
        SousCategorie SousCategorie86 = new SousCategorie("Burger");
        SousCategorie SousCategorie87 = new SousCategorie("Paris-Brest");
        SousCategorie SousCategorie88 = new SousCategorie("Quiche");
        SousCategorie SousCategorie89 = new SousCategorie("Salsifis");
        SousCategorie SousCategorie90 = new SousCategorie("Brownie");
        SousCategorie SousCategorie91 = new SousCategorie("Panini");
        SousCategorie SousCategorie92 = new SousCategorie("Cannelés");
        SousCategorie SousCategorie93 = new SousCategorie("Croque");
        SousCategorie SousCategorie94 = new SousCategorie("Fudge");
        SousCategorie SousCategorie95 = new SousCategorie("Damier");
        SousCategorie SousCategorie96 = new SousCategorie("Patate");
        SousCategorie SousCategorie97 = new SousCategorie("Chili");
        SousCategorie SousCategorie99 = new SousCategorie("Curry");
        SousCategorie SousCategorie100 = new SousCategorie("Cannelonni");
        SousCategorie SousCategorie101 = new SousCategorie("Pomme");
        SousCategorie SousCategorie102 = new SousCategorie("Nems");
        SousCategorie SousCategorie103 = new SousCategorie("Muffin");
        SousCategorie SousCategorie104 = new SousCategorie("Choux");
        SousCategorie SousCategorie105 = new SousCategorie("Couronne");
        SousCategorie SousCategorie106 = new SousCategorie("Crêpes");
        SousCategorie SousCategorie107 = new SousCategorie("Mystère");
        SousCategorie SousCategorie108 = new SousCategorie("Frites");
        SousCategorie SousCategorie109 = new SousCategorie("Muffins");
        SousCategorie SousCategorie110 = new SousCategorie("Croque-madame");
        SousCategorie SousCategorie111 = new SousCategorie("Bouillon");
        SousCategorie SousCategorie112 = new SousCategorie("Reblochon");
        SousCategorie SousCategorie113 = new SousCategorie("diots");
        SousCategorie SousCategorie114 = new SousCategorie("Biscuit");
        SousCategorie SousCategorie115 = new SousCategorie("Crevettes");
        SousCategorie SousCategorie116 = new SousCategorie("Pavé");
        SousCategorie SousCategorie117 = new SousCategorie("Bavarois");
        SousCategorie SousCategorie118 = new SousCategorie("Ecume");
        SousCategorie SousCategorie119 = new SousCategorie("Bourguignon");
        SousCategorie SousCategorie120 = new SousCategorie("Zoodle");
        SousCategorie SousCategorie121 = new SousCategorie("Galette");

        // 4: TVA
        TVA TVA = new TVA(10f, "TVA intermédiaire");

        // 5: Statut
        Statut sproduit1 = new Statut(1, "Disponible");
        Statut sproduit2 = new Statut(1, "Indisponible");
        Statut smenu1 = new Statut(10, "Disponible");
        em.persist(smenu1);

        // 6: Produit
        Produit p1 = new Produit("Soupe froide à la tomate", 7f, "1.jpg", null, 8, true, false);
        SousCategorie1.setCategorieProduit(CategorieProduit1);
        p1.setSousCategorie(SousCategorie1);
        p1.setStatut(sproduit1);
        Produit p6 = new Produit("Carpaccio de courgettes", 6f, "6.jpg", null, 12, true, false);
        SousCategorie6.setCategorieProduit(CategorieProduit1);
        p6.setSousCategorie(SousCategorie6);
        p6.setStatut(sproduit1);
        Produit p11 = new Produit("Melon aux crevettes", 6f, "11.jpg", null, 12, true, false);
        SousCategorie11.setCategorieProduit(CategorieProduit1);
        p11.setSousCategorie(SousCategorie11);
        p11.setStatut(sproduit1);
        Produit p16 = new Produit("Tarte aux aubergines, tomates et parmesan", 10f, "16.jpg", null, 10, true, false);
        SousCategorie15.setCategorieProduit(CategorieProduit1);
        p16.setSousCategorie(SousCategorie15);
        p16.setStatut(sproduit1);
        Produit p21 = new Produit("Fleurs de courgettes au chèvre frais et à la menthe", 11f, "21.jpg", null, 5, true, false);
        SousCategorie19.setCategorieProduit(CategorieProduit1);
        p21.setSousCategorie(SousCategorie19);
        p21.setStatut(sproduit1);
        Produit p26 = new Produit("Salade de kiwis et tomates de Lili", 8f, "26.jpg", null, 5, true, false);
        SousCategorie5.setCategorieProduit(CategorieProduit1);
        p26.setSousCategorie(SousCategorie5);
        p26.setStatut(sproduit1);
        Produit p30 = new Produit("Cromesqui de Neufchâtel AOP de Normandie, figues et framboises", 11f, "30.jpg", null, 11, true, false);
        SousCategorie27.setCategorieProduit(CategorieProduit1);
        p30.setSousCategorie(SousCategorie27);
        p30.setStatut(sproduit1);
        Produit p36 = new Produit("Tartine avocat et son oeuf mollet", 8f, "36.jpg", null, 9, true, false);
        SousCategorie33.setCategorieProduit(CategorieProduit1);
        p36.setSousCategorie(SousCategorie33);
        p36.setStatut(sproduit1);
        Produit p41 = new Produit("Aubergines à la parmesane", 8f, "41.jpg", null, 7, true, false);
        SousCategorie38.setCategorieProduit(CategorieProduit1);
        p41.setSousCategorie(SousCategorie38);
        p41.setStatut(sproduit1);
        Produit p46 = new Produit("Soufflés au fromage et à la ciboulette", 12f, "46.jpg", null, 11, true, false);
        SousCategorie43.setCategorieProduit(CategorieProduit1);
        p46.setSousCategorie(SousCategorie43);
        p46.setStatut(sproduit1);
        Produit p47 = new Produit("Salade de quinoa à la feta", 6f, "47.jpg", null, 5, true, false);
        SousCategorie5.setCategorieProduit(CategorieProduit1);
        p47.setSousCategorie(SousCategorie5);
        p47.setStatut(sproduit1);
        Produit p56 = new Produit("Tarte tomates sur pâte filo", 8f, "56.jpg", null, 11, true, false);
        SousCategorie15.setCategorieProduit(CategorieProduit1);
        p56.setSousCategorie(SousCategorie15);
        p56.setStatut(sproduit1);
        Produit p61 = new Produit("Velouté glacé à la courgette", 8f, "61.jpg", null, 7, true, false);
        SousCategorie52.setCategorieProduit(CategorieProduit1);
        p61.setSousCategorie(SousCategorie52);
        p61.setStatut(sproduit1);
        Produit p71 = new Produit("Oeuf cocotte en tasse de jambon", 11f, "71.jpg", null, 9, true, false);
        SousCategorie60.setCategorieProduit(CategorieProduit1);
        p71.setSousCategorie(SousCategorie60);
        p71.setStatut(sproduit1);
        Produit p76 = new Produit("Pâté de Pâques berrichon", 8f, "76.jpg", null, 7, true, false);
        SousCategorie65.setCategorieProduit(CategorieProduit1);
        p76.setSousCategorie(SousCategorie65);
        p76.setStatut(sproduit1);
        Produit p81 = new Produit("Salade de crevettes et de pamplemousse rose", 7f, "81.jpg", null, 10, true, false);
        SousCategorie5.setCategorieProduit(CategorieProduit1);
        p81.setSousCategorie(SousCategorie5);
        p81.setStatut(sproduit1);
        Produit p86 = new Produit("Popcorn chou-fleur", 12f, "86.jpg", null, 6, true, false);
        SousCategorie73.setCategorieProduit(CategorieProduit1);
        p86.setSousCategorie(SousCategorie73);
        p86.setStatut(sproduit1);
        Produit p95 = new Produit("Bouchée croustillante de dinde au pesto", 12f, "95.jpg", null, 10, true, false);
        SousCategorie79.setCategorieProduit(CategorieProduit1);
        p95.setSousCategorie(SousCategorie79);
        p95.setStatut(sproduit1);
        Produit p106 = new Produit("Tarte saumon et épinards", 11f, "106.jpg", null, 5, true, false);
        SousCategorie15.setCategorieProduit(CategorieProduit1);
        p106.setSousCategorie(SousCategorie15);
        p106.setStatut(sproduit1);
        Produit p121 = new Produit("Bowl cake façon brunch", 6f, "121.jpg", null, 12, true, false);
        SousCategorie48.setCategorieProduit(CategorieProduit1);
        p121.setSousCategorie(SousCategorie48);
        p121.setStatut(sproduit1);
        Produit p126 = new Produit("Muffin quinoa épinard tomates séchées", 8f, "126.jpg", null, 10, true, false);
        SousCategorie103.setCategorieProduit(CategorieProduit1);
        p126.setSousCategorie(SousCategorie103);
        p126.setStatut(sproduit1);
        Produit p136 = new Produit("Bouillon pho (Vietnam)", 8f, "136.jpg", null, 8, true, false);
        SousCategorie111.setCategorieProduit(CategorieProduit1);
        p136.setSousCategorie(SousCategorie111);
        p136.setStatut(sproduit1);
        Produit p141 = new Produit("Crevettes panées", 10f, "141.jpg", null, 5, true, false);
        SousCategorie115.setCategorieProduit(CategorieProduit1);
        p141.setSousCategorie(SousCategorie115);
        p141.setStatut(sproduit1);
        Produit p146 = new Produit("Ecume de cola sur chips de bacon", 9f, "146.jpg", null, 8, true, false);
        SousCategorie118.setCategorieProduit(CategorieProduit1);
        p146.setSousCategorie(SousCategorie118);
        p146.setStatut(sproduit1);
        Produit p2 = new Produit("Paella rapide", 13f, "2.jpg", null, 5, true, false);
        SousCategorie2.setCategorieProduit(CategorieProduit2);
        p2.setSousCategorie(SousCategorie2);
        p2.setStatut(sproduit1);
        Produit p3 = new Produit("Bruschetta", 14f, "3.jpg", null, 6, true, false);
        SousCategorie3.setCategorieProduit(CategorieProduit2);
        p3.setSousCategorie(SousCategorie3);
        p3.setStatut(sproduit1);
        Produit p5 = new Produit("Salade vitaminée du dimanche soir", 11f, "5.jpg", null, 8, true, false);
        SousCategorie5.setCategorieProduit(CategorieProduit2);
        p5.setSousCategorie(SousCategorie5);
        p5.setStatut(sproduit1);
        Produit p8 = new Produit("Tartare de saumon", 19f, "8.jpg", null, 6, true, false);
        SousCategorie8.setCategorieProduit(CategorieProduit2);
        p8.setSousCategorie(SousCategorie8);
        p8.setStatut(sproduit1);
        Produit p12 = new Produit("Filet mignon en croûte", 18f, "12.jpg", null, 6, true, false);
        SousCategorie12.setCategorieProduit(CategorieProduit2);
        p12.setSousCategorie(SousCategorie12);
        p12.setStatut(sproduit1);
        Produit p13 = new Produit("Salade de raie aux haricots verts", 16f, "13.jpg", null, 10, true, false);
        SousCategorie5.setCategorieProduit(CategorieProduit2);
        p13.setSousCategorie(SousCategorie5);
        p13.setStatut(sproduit1);
        Produit p17 = new Produit("Poulet basquaise", 12f, "17.jpg", null, 6, true, false);
        SousCategorie16.setCategorieProduit(CategorieProduit2);
        p17.setSousCategorie(SousCategorie16);
        p17.setStatut(sproduit1);
        Produit p20 = new Produit("Moules au barbecue farcies gratinées au parmesan", 15f, "20.jpg", null, 8, true, false);
        SousCategorie18.setCategorieProduit(CategorieProduit2);
        p20.setSousCategorie(SousCategorie18);
        p20.setStatut(sproduit1);
        Produit p22 = new Produit("spaghettis aux calamars", 13f, "22.jpg", null, 6, true, false);
        SousCategorie20.setCategorieProduit(CategorieProduit2);
        p22.setSousCategorie(SousCategorie20);
        p22.setStatut(sproduit1);
        Produit p23 = new Produit("Lapin au citron", 18f, "23.jpg", null, 10, true, false);
        SousCategorie21.setCategorieProduit(CategorieProduit2);
        p23.setSousCategorie(SousCategorie21);
        p23.setStatut(sproduit1);
        Produit p25 = new Produit("Aiguillettes de poulet laquées au ketchup servies avec ses frites de légumes", 10f, "25.jpg", null, 10, true, false);
        SousCategorie23.setCategorieProduit(CategorieProduit2);
        p25.setSousCategorie(SousCategorie23);
        p25.setStatut(sproduit1);
        Produit p27 = new Produit("Lasagnes aux courgettes et au chèvre", 19f, "27.jpg", null, 8, true, false);
        SousCategorie24.setCategorieProduit(CategorieProduit2);
        p27.setSousCategorie(SousCategorie24);
        p27.setStatut(sproduit1);
        Produit p32 = new Produit("Wok de concombres et saumon", 13f, "32.jpg", null, 5, true, false);
        SousCategorie29.setCategorieProduit(CategorieProduit2);
        p32.setSousCategorie(SousCategorie29);
        p32.setStatut(sproduit1);
        Produit p33 = new Produit("Omelette à la feta", 10f, "33.jpg", null, 5, true, false);
        SousCategorie30.setCategorieProduit(CategorieProduit2);
        p33.setSousCategorie(SousCategorie30);
        p33.setStatut(sproduit1);
        Produit p38 = new Produit("Nuggets de quinoa", 13f, "38.jpg", null, 10, true, false);
        SousCategorie35.setCategorieProduit(CategorieProduit2);
        p38.setSousCategorie(SousCategorie35);
        p38.setStatut(sproduit1);
        Produit p42 = new Produit("Croq' baguette", 15f, "42.jpg", null, 12, true, false);
        SousCategorie39.setCategorieProduit(CategorieProduit2);
        p42.setSousCategorie(SousCategorie39);
        p42.setStatut(sproduit1);
        Produit p48 = new Produit("Pizza chou-fleur et roquette", 17f, "48.jpg", null, 12, true, false);
        SousCategorie44.setCategorieProduit(CategorieProduit2);
        p48.setSousCategorie(SousCategorie44);
        p48.setStatut(sproduit1);
        Produit p52 = new Produit("One Pot Pasta de farfalles crémeuses au poulet", 19f, "52.jpg", null, 8, true, false);
        SousCategorie47.setCategorieProduit(CategorieProduit2);
        p52.setSousCategorie(SousCategorie47);
        p52.setStatut(sproduit1);
        Produit p53 = new Produit("Pizza tortilla", 10f, "53.jpg", null, 5, true, false);
        SousCategorie44.setCategorieProduit(CategorieProduit2);
        p53.setSousCategorie(SousCategorie44);
        p53.setStatut(sproduit1);
        Produit p57 = new Produit("Salade grecque façon buddha bowl", 13f, "57.jpg", null, 7, true, false);
        SousCategorie5.setCategorieProduit(CategorieProduit2);
        p57.setSousCategorie(SousCategorie5);
        p57.setStatut(sproduit1);
        Produit p58 = new Produit("Risotto de pâtes d'Elodie", 19f, "58.jpg", null, 7, true, false);
        SousCategorie50.setCategorieProduit(CategorieProduit2);
        p58.setSousCategorie(SousCategorie50);
        p58.setStatut(sproduit1);
        Produit p62 = new Produit("canard sauvage aux petits pois", 13f, "62.jpg", null, 11, true, false);
        SousCategorie53.setCategorieProduit(CategorieProduit2);
        p62.setSousCategorie(SousCategorie53);
        p62.setStatut(sproduit1);
        Produit p63 = new Produit("Poke bowl avocat et thon mariné", 18f, "63.jpg", null, 8, true, false);
        SousCategorie54.setCategorieProduit(CategorieProduit2);
        p63.setSousCategorie(SousCategorie54);
        p63.setStatut(sproduit1);
        Produit p67 = new Produit("Cordon bleu roulé", 18f, "67.jpg", null, 5, true, false);
        SousCategorie58.setCategorieProduit(CategorieProduit2);
        p67.setSousCategorie(SousCategorie58);
        p67.setStatut(sproduit1);
        Produit p68 = new Produit("Velouté de petit pois façon Julie", 12f, "68.jpg", null, 5, true, false);
        SousCategorie52.setCategorieProduit(CategorieProduit2);
        p68.setSousCategorie(SousCategorie52);
        p68.setStatut(sproduit1);
        Produit p72 = new Produit("Agneau confit aux pommes de terres nouvelles", 13f, "72.jpg", null, 8, true, false);
        SousCategorie61.setCategorieProduit(CategorieProduit2);
        p72.setSousCategorie(SousCategorie61);
        p72.setStatut(sproduit1);
        Produit p77 = new Produit("Gigot pleureur", 16f, "77.jpg", null, 5, true, false);
        SousCategorie66.setCategorieProduit(CategorieProduit2);
        p77.setSousCategorie(SousCategorie66);
        p77.setStatut(sproduit1);
        Produit p78 = new Produit("Risotto aux asperges fraîches", 17f, "78.jpg", null, 9, true, false);
        SousCategorie50.setCategorieProduit(CategorieProduit2);
        p78.setSousCategorie(SousCategorie50);
        p78.setStatut(sproduit1);
        Produit p82 = new Produit("Saucisses aux lentilles ", 16f, "82.jpg", null, 6, true, false);
        SousCategorie69.setCategorieProduit(CategorieProduit2);
        p82.setSousCategorie(SousCategorie69);
        p82.setStatut(sproduit1);
        Produit p83 = new Produit("Blanquette de veau façon phô", 13f, "83.jpg", null, 9, true, false);
        SousCategorie70.setCategorieProduit(CategorieProduit2);
        p83.setSousCategorie(SousCategorie70);
        p83.setStatut(sproduit1);
        Produit p87 = new Produit("Pizza gaufrée au fromage", 10f, "87.jpg", null, 11, true, false);
        SousCategorie44.setCategorieProduit(CategorieProduit2);
        p87.setSousCategorie(SousCategorie44);
        p87.setStatut(sproduit1);
        Produit p90 = new Produit("Gaufre feuilletée chèvre épinard du dimanche soir", 18f, "90.jpg", null, 10, true, false);
        SousCategorie75.setCategorieProduit(CategorieProduit2);
        p90.setSousCategorie(SousCategorie75);
        p90.setStatut(sproduit1);
        Produit p92 = new Produit("Boulettes de Tata Simone", 14f, "92.jpg", null, 7, true, false);
        SousCategorie57.setCategorieProduit(CategorieProduit2);
        p92.setSousCategorie(SousCategorie57);
        p92.setStatut(sproduit1);
        Produit p93 = new Produit("Gratin butternut pommes de terre et coco", 15f, "93.jpg", null, 6, true, false);
        SousCategorie77.setCategorieProduit(CategorieProduit2);
        p93.setSousCategorie(SousCategorie77);
        p93.setStatut(sproduit1);
        Produit p98 = new Produit("Gratin de pâtes au thon, mozzarella", 11f, "98.jpg", null, 8, true, false);
        SousCategorie77.setCategorieProduit(CategorieProduit2);
        p98.setSousCategorie(SousCategorie77);
        p98.setStatut(sproduit1);
        Produit p102 = new Produit("Pad Thai", 10f, "102.jpg", null, 7, true, false);
        SousCategorie85.setCategorieProduit(CategorieProduit2);
        p102.setSousCategorie(SousCategorie85);
        p102.setStatut(sproduit1);
        Produit p103 = new Produit("Burger croustillant", 12f, "103.jpg", null, 10, true, false);
        SousCategorie86.setCategorieProduit(CategorieProduit2);
        p103.setSousCategorie(SousCategorie86);
        p103.setStatut(sproduit1);
        Produit p105 = new Produit("Quiche façon lorraine au thon", 10f, "105.jpg", null, 8, true, false);
        SousCategorie88.setCategorieProduit(CategorieProduit2);
        p105.setSousCategorie(SousCategorie88);
        p105.setStatut(sproduit1);
        Produit p107 = new Produit("Gaufre burger aux oeufs Bénédicte", 12f, "107.jpg", null, 11, true, false);
        SousCategorie75.setCategorieProduit(CategorieProduit2);
        p107.setSousCategorie(SousCategorie75);
        p107.setStatut(sproduit1);
        Produit p110 = new Produit("Panini rustique sans gluten", 20f, "110.jpg", null, 7, true, false);
        SousCategorie91.setCategorieProduit(CategorieProduit2);
        p110.setSousCategorie(SousCategorie91);
        p110.setStatut(sproduit1);
        Produit p113 = new Produit("Croque madame revisité aux galettes de sarrasin", 14f, "113.jpg", null, 11, true, false);
        SousCategorie93.setCategorieProduit(CategorieProduit2);
        p113.setSousCategorie(SousCategorie93);
        p113.setStatut(sproduit1);
        Produit p115 = new Produit("Bagel brie, miel et noix", 14f, "115.jpg", null, 5, true, false);
        SousCategorie45.setCategorieProduit(CategorieProduit2);
        p115.setSousCategorie(SousCategorie45);
        p115.setStatut(sproduit1);
        Produit p117 = new Produit("Patate douce farcie quinoa et brocoli", 18f, "117.jpg", null, 8, true, false);
        SousCategorie96.setCategorieProduit(CategorieProduit2);
        p117.setSousCategorie(SousCategorie96);
        p117.setStatut(sproduit1);
        Produit p118 = new Produit("Chili con carne express", 13f, "118.jpg", null, 12, true, false);
        SousCategorie97.setCategorieProduit(CategorieProduit2);
        p118.setSousCategorie(SousCategorie97);
        p118.setStatut(sproduit1);
        Produit p122 = new Produit("Curry thaï à la japonaise", 14f, "122.jpg", null, 9, true, false);
        SousCategorie99.setCategorieProduit(CategorieProduit2);
        p122.setSousCategorie(SousCategorie99);
        p122.setStatut(sproduit1);
        Produit p123 = new Produit("Cannelonni au chili con carne", 10f, "123.jpg", null, 9, true, false);
        SousCategorie100.setCategorieProduit(CategorieProduit2);
        p123.setSousCategorie(SousCategorie100);
        p123.setStatut(sproduit1);
        Produit p127 = new Produit("Gâteau de pain perdu jambon mozzarella", 11f, "127.jpg", null, 12, true, false);
        SousCategorie63.setCategorieProduit(CategorieProduit2);
        p127.setSousCategorie(SousCategorie63);
        p127.setStatut(sproduit1);
        Produit p132 = new Produit("Riz sauté à l'ananas", 12f, "132.jpg", null, 12, true, false);
        SousCategorie62.setCategorieProduit(CategorieProduit2);
        p132.setSousCategorie(SousCategorie62);
        p132.setStatut(sproduit1);
        Produit p135 = new Produit("Croque-madame mozzarella mâche jambon", 10f, "135.jpg", null, 5, true, false);
        SousCategorie110.setCategorieProduit(CategorieProduit2);
        p135.setSousCategorie(SousCategorie110);
        p135.setStatut(sproduit1);
        Produit p137 = new Produit("Reblochon farci façon Tartiflette", 11f, "137.jpg", null, 10, true, false);
        SousCategorie112.setCategorieProduit(CategorieProduit2);
        p137.setSousCategorie(SousCategorie112);
        p137.setStatut(sproduit1);
        Produit p138 = new Produit("diots savoyards au vin blanc", 20f, "138.jpg", null, 11, true, false);
        SousCategorie113.setCategorieProduit(CategorieProduit2);
        p138.setSousCategorie(SousCategorie113);
        p138.setStatut(sproduit1);
        Produit p140 = new Produit("boeuf carottes", 16f, "140.jpg", null, 11, true, false);
        SousCategorie67.setCategorieProduit(CategorieProduit2);
        p140.setSousCategorie(SousCategorie67);
        p140.setStatut(sproduit1);
        Produit p142 = new Produit("Pomme de terre garnie façon raclette", 10f, "142.jpg", null, 11, true, false);
        SousCategorie101.setCategorieProduit(CategorieProduit2);
        p142.setSousCategorie(SousCategorie101);
        p142.setStatut(sproduit1);
        Produit p143 = new Produit("Pavé de saumon sur son lit de poireaux", 18f, "143.jpg", null, 6, true, false);
        SousCategorie116.setCategorieProduit(CategorieProduit2);
        p143.setSousCategorie(SousCategorie116);
        p143.setStatut(sproduit1);
        Produit p145 = new Produit("Omelette roulée surimi fromage et ciboulette", 15f, "145.jpg", null, 5, true, false);
        SousCategorie30.setCategorieProduit(CategorieProduit2);
        p145.setSousCategorie(SousCategorie30);
        p145.setStatut(sproduit1);
        Produit p147 = new Produit("Bourguignon délicieux", 12f, "147.jpg", null, 6, true, false);
        SousCategorie119.setCategorieProduit(CategorieProduit2);
        p147.setSousCategorie(SousCategorie119);
        p147.setStatut(sproduit1);
        Produit p150 = new Produit("Chili con carne", 19f, "150.jpg", null, 11, true, false);
        SousCategorie97.setCategorieProduit(CategorieProduit2);
        p150.setSousCategorie(SousCategorie97);
        p150.setStatut(sproduit1);
        Produit p4 = new Produit("Crème au cassis", 5f, "4.jpg", null, 7, true, false);
        SousCategorie4.setCategorieProduit(CategorieProduit3);
        p4.setSousCategorie(SousCategorie4);
        p4.setStatut(sproduit1);
        Produit p9 = new Produit("Fondant au chocolat plus que fondant", 9f, "9.jpg", null, 10, true, false);
        SousCategorie9.setCategorieProduit(CategorieProduit3);
        p9.setSousCategorie(SousCategorie9);
        p9.setStatut(sproduit1);
        Produit p14 = new Produit("charlotte aux fraises", 9f, "14.jpg", null, 12, true, false);
        SousCategorie13.setCategorieProduit(CategorieProduit3);
        p14.setSousCategorie(SousCategorie13);
        p14.setStatut(sproduit1);
        Produit p19 = new Produit("Clafoutis grand-mère aux cerises", 9f, "19.jpg", null, 6, true, false);
        SousCategorie17.setCategorieProduit(CategorieProduit3);
        p19.setSousCategorie(SousCategorie17);
        p19.setStatut(sproduit1);
        Produit p24 = new Produit("Tarte aux fraises", 10f, "24.jpg", null, 10, true, false);
        SousCategorie15.setCategorieProduit(CategorieProduit3);
        p24.setSousCategorie(SousCategorie15);
        p24.setStatut(sproduit1);
        Produit p29 = new Produit("Financiers aux myrtilles", 9f, "29.jpg", null, 11, true, false);
        SousCategorie26.setCategorieProduit(CategorieProduit3);
        p29.setSousCategorie(SousCategorie26);
        p29.setStatut(sproduit1);
        Produit p34 = new Produit("Chouquettes au beurre de cacahuètes", 7f, "34.jpg", null, 8, true, false);
        SousCategorie31.setCategorieProduit(CategorieProduit3);
        p34.setSousCategorie(SousCategorie31);
        p34.setStatut(sproduit1);
        Produit p35 = new Produit("Granola maison", 5f, "35.jpg", null, 5, true, false);
        SousCategorie32.setCategorieProduit(CategorieProduit3);
        p35.setSousCategorie(SousCategorie32);
        p35.setStatut(sproduit1);
        Produit p39 = new Produit("Brioche", 7f, "39.jpg", null, 6, true, false);
        SousCategorie36.setCategorieProduit(CategorieProduit3);
        p39.setSousCategorie(SousCategorie36);
        p39.setStatut(sproduit1);
        Produit p44 = new Produit("Crumble banane chocolat speculoos revisité façon glacé", 5f, "44.jpg", null, 11, true, false);
        SousCategorie41.setCategorieProduit(CategorieProduit3);
        p44.setSousCategorie(SousCategorie41);
        p44.setStatut(sproduit1);
        Produit p49 = new Produit("Roulé au nutella", 7f, "49.jpg", null, 12, true, false);
        SousCategorie28.setCategorieProduit(CategorieProduit3);
        p49.setSousCategorie(SousCategorie28);
        p49.setStatut(sproduit1);
        Produit p50 = new Produit("Bagel crème de coco, ananas et zeste de citron", 5f, "50.jpg", null, 6, true, false);
        SousCategorie45.setCategorieProduit(CategorieProduit3);
        p50.setSousCategorie(SousCategorie45);
        p50.setStatut(sproduit1);
        Produit p54 = new Produit("Bowl cake moelleux chocolat noisettes", 7f, "54.jpg", null, 7, true, false);
        SousCategorie48.setCategorieProduit(CategorieProduit3);
        p54.setSousCategorie(SousCategorie48);
        p54.setStatut(sproduit1);
        Produit p59 = new Produit("Rouleau de printemps aux fruits", 7f, "59.jpg", null, 9, true, false);
        SousCategorie51.setCategorieProduit(CategorieProduit3);
        p59.setSousCategorie(SousCategorie51);
        p59.setStatut(sproduit1);
        Produit p60 = new Produit("Smoothie bowl mangue coco graines de chia", 9f, "60.jpg", null, 7, true, false);
        SousCategorie37.setCategorieProduit(CategorieProduit3);
        p60.setSousCategorie(SousCategorie37);
        p60.setStatut(sproduit1);
        Produit p64 = new Produit("Tartelettes aux fruits", 7f, "64.jpg", null, 5, true, false);
        SousCategorie55.setCategorieProduit(CategorieProduit3);
        p64.setSousCategorie(SousCategorie55);
        p64.setStatut(sproduit1);
        Produit p74 = new Produit("Gâteau marbré en coquille d'oeuf", 6f, "74.jpg", null, 12, true, false);
        SousCategorie63.setCategorieProduit(CategorieProduit3);
        p74.setSousCategorie(SousCategorie63);
        p74.setStatut(sproduit1);
        Produit p79 = new Produit("Le potager cookie à manger", 8f, "79.jpg", null, 11, true, false);
        SousCategorie67.setCategorieProduit(CategorieProduit3);
        p79.setSousCategorie(SousCategorie67);
        p79.setStatut(sproduit1);
        Produit p80 = new Produit("Dessert Grand Ferrero Rocher", 6f, "80.jpg", null, 10, true, false);
        SousCategorie68.setCategorieProduit(CategorieProduit3);
        p80.setSousCategorie(SousCategorie68);
        p80.setStatut(sproduit1);
        Produit p84 = new Produit("Crottes de licorne", 7f, "84.jpg", null, 7, true, false);
        SousCategorie71.setCategorieProduit(CategorieProduit3);
        p84.setSousCategorie(SousCategorie71);
        p84.setStatut(sproduit1);
        Produit p85 = new Produit("Millefeuille de chocolat au lait", 9f, "85.jpg", null, 10, true, false);
        SousCategorie72.setCategorieProduit(CategorieProduit3);
        p85.setSousCategorie(SousCategorie72);
        p85.setStatut(sproduit1);
        Produit p89 = new Produit("Gaufre / Brownies", 8f, "89.jpg", null, 12, true, false);
        SousCategorie75.setCategorieProduit(CategorieProduit3);
        p89.setSousCategorie(SousCategorie75);
        p89.setStatut(sproduit1);
        Produit p94 = new Produit("Pancakes à la japonaise", 10f, "94.jpg", null, 12, true, false);
        SousCategorie78.setCategorieProduit(CategorieProduit3);
        p94.setSousCategorie(SousCategorie78);
        p94.setStatut(sproduit1);
        Produit p99 = new Produit("Iles flottantes coeur caramel", 6f, "99.jpg", null, 6, true, false);
        SousCategorie82.setCategorieProduit(CategorieProduit3);
        p99.setSousCategorie(SousCategorie82);
        p99.setStatut(sproduit1);
        Produit p100 = new Produit("Douceur de chocolat aux amandes", 6f, "100.jpg", null, 10, true, false);
        SousCategorie83.setCategorieProduit(CategorieProduit3);
        p100.setSousCategorie(SousCategorie83);
        p100.setStatut(sproduit1);
        Produit p104 = new Produit("Paris-Brest généreux", 7f, "104.jpg", null, 7, true, false);
        SousCategorie87.setCategorieProduit(CategorieProduit3);
        p104.setSousCategorie(SousCategorie87);
        p104.setStatut(sproduit1);
        Produit p109 = new Produit("Brownie vite fait", 8f, "109.jpg", null, 11, true, false);
        SousCategorie90.setCategorieProduit(CategorieProduit3);
        p109.setSousCategorie(SousCategorie90);
        p109.setStatut(sproduit1);
        Produit p119 = new Produit("Riz soufflé de la Saint Valentin", 10f, "119.jpg", null, 12, true, false);
        SousCategorie62.setCategorieProduit(CategorieProduit3);
        p119.setSousCategorie(SousCategorie62);
        p119.setStatut(sproduit1);
        Produit p120 = new Produit("Charlotte aux fruits au mascarpone", 6f, "120.jpg", null, 7, true, false);
        SousCategorie13.setCategorieProduit(CategorieProduit3);
        p120.setSousCategorie(SousCategorie13);
        p120.setStatut(sproduit1);
        Produit p124 = new Produit("Pomme au caramel façon pomme d'amour", 9f, "124.jpg", null, 9, true, false);
        SousCategorie101.setCategorieProduit(CategorieProduit3);
        p124.setSousCategorie(SousCategorie101);
        p124.setStatut(sproduit1);
        Produit p125 = new Produit("Nems croustillants fruits et chocolat", 10f, "125.jpg", null, 12, true, false);
        SousCategorie102.setCategorieProduit(CategorieProduit3);
        p125.setSousCategorie(SousCategorie102);
        p125.setStatut(sproduit1);
        Produit p129 = new Produit("Couronne chocolat pistache", 7f, "129.jpg", null, 7, true, false);
        SousCategorie105.setCategorieProduit(CategorieProduit3);
        p129.setSousCategorie(SousCategorie105);
        p129.setStatut(sproduit1);
        Produit p130 = new Produit("Crêpes 5C", 6f, "130.jpg", null, 5, true, false);
        SousCategorie106.setCategorieProduit(CategorieProduit3);
        p130.setSousCategorie(SousCategorie106);
        p130.setStatut(sproduit1);
        Produit p134 = new Produit("Muffins renversés à la clémentine", 8f, "134.jpg", null, 6, true, false);
        SousCategorie109.setCategorieProduit(CategorieProduit3);
        p134.setSousCategorie(SousCategorie109);
        p134.setStatut(sproduit1);
        Produit p139 = new Produit("Biscuit façon crème brûlée", 9f, "139.jpg", null, 7, true, false);
        SousCategorie114.setCategorieProduit(CategorieProduit3);
        p139.setSousCategorie(SousCategorie114);
        p139.setStatut(sproduit1);
        Produit p144 = new Produit("Bavarois façon bounty", 8f, "144.jpg", null, 12, true, false);
        SousCategorie117.setCategorieProduit(CategorieProduit3);
        p144.setSousCategorie(SousCategorie117);
        p144.setStatut(sproduit1);
        Produit p149 = new Produit("Galette des rois", 6f, "149.jpg", null, 9, true, false);
        SousCategorie121.setCategorieProduit(CategorieProduit3);
        p149.setSousCategorie(SousCategorie121);
        p149.setStatut(sproduit1);
        Produit p7 = new Produit("Jardinière de légumes avec laitue", 3f, "7.jpg", null, 5, true, false);
        SousCategorie7.setCategorieProduit(CategorieProduit4);
        p7.setSousCategorie(SousCategorie7);
        p7.setStatut(sproduit1);
        Produit p18 = new Produit("Melon en salade", 6f, "18.jpg", null, 11, true, false);
        SousCategorie11.setCategorieProduit(CategorieProduit1);
        p18.setSousCategorie(SousCategorie11);
        p18.setStatut(sproduit1);
        Produit p28 = new Produit("Fagots de haricots verts", 4f, "28.jpg", null, 8, true, false);
        SousCategorie25.setCategorieProduit(CategorieProduit4);
        p28.setSousCategorie(SousCategorie25);
        p28.setStatut(sproduit1);
        Produit p37 = new Produit("Tian d'aubergines", 8f, "37.jpg", null, 10, true, false);
        SousCategorie34.setCategorieProduit(CategorieProduit4);
        p37.setSousCategorie(SousCategorie34);
        p37.setStatut(sproduit1);
        Produit p43 = new Produit("Beignets de salade", 3f, "43.jpg", null, 12, true, false);
        SousCategorie40.setCategorieProduit(CategorieProduit4);
        p43.setSousCategorie(SousCategorie40);
        p43.setStatut(sproduit1);
        Produit p73 = new Produit("Riz aux épinards", 7f, "73.jpg", null, 8, true, false);
        SousCategorie62.setCategorieProduit(CategorieProduit4);
        p73.setSousCategorie(SousCategorie62);
        p73.setStatut(sproduit1);
        Produit p97 = new Produit("Purée de brocoli sur lit de boulgour", 5f, "97.jpg", null, 6, true, false);
        SousCategorie81.setCategorieProduit(CategorieProduit4);
        p97.setSousCategorie(SousCategorie81);
        p97.setStatut(sproduit1);
        Produit p108 = new Produit("Salsifis croustillants", 6f, "108.jpg", null, 8, true, false);
        SousCategorie89.setCategorieProduit(CategorieProduit4);
        p108.setSousCategorie(SousCategorie89);
        p108.setStatut(sproduit1);
        Produit p112 = new Produit("Gratin dauphinois (recette originale)", 3f, "112.jpg", null, 9, true, false);
        SousCategorie77.setCategorieProduit(CategorieProduit4);
        p112.setSousCategorie(SousCategorie77);
        p112.setStatut(sproduit1);
        Produit p128 = new Produit("Choux de Bruxelles frits", 5f, "128.jpg", null, 8, true, false);
        SousCategorie104.setCategorieProduit(CategorieProduit4);
        p128.setSousCategorie(SousCategorie104);
        p128.setStatut(sproduit1);
        Produit p133 = new Produit("Frites d'avocat", 5f, "133.jpg", null, 7, true, false);
        SousCategorie108.setCategorieProduit(CategorieProduit4);
        p133.setSousCategorie(SousCategorie108);
        p133.setStatut(sproduit1);
        Produit p148 = new Produit("Zoodle de butternut", 6f, "148.jpg", null, 7, true, false);
        SousCategorie120.setCategorieProduit(CategorieProduit4);
        p148.setSousCategorie(SousCategorie120);
        p148.setStatut(sproduit1);
        Produit p10 = new Produit("Guacamole au pesto", 8f, "10.jpg", null, 5, true, false);
        SousCategorie10.setCategorieProduit(CategorieProduit5);
        p10.setSousCategorie(SousCategorie10);
        p10.setStatut(sproduit1);
        Produit p15 = new Produit("L'antioxydant gourmand : myrtilles, framboises, betterave...", 7f, "15.jpg", null, 9, true, false);
        SousCategorie14.setCategorieProduit(CategorieProduit6);
        p15.setSousCategorie(SousCategorie14);
        p15.setStatut(sproduit1);
        Produit p40 = new Produit("Smoothie fruits rouges", 4f, "40.jpg", null, 10, true, false);
        SousCategorie37.setCategorieProduit(CategorieProduit6);
        p40.setSousCategorie(SousCategorie37);
        p40.setStatut(sproduit1);
        Produit p65 = new Produit("Booster de Printemps : mâche, mangue, banane...", 7f, "65.jpg", null, 7, true, false);
        SousCategorie56.setCategorieProduit(CategorieProduit6);
        p65.setSousCategorie(SousCategorie56);
        p65.setStatut(sproduit1);
        Produit p31 = new Produit("Roulé apéritif tricolore au fromage", 4f, "31.jpg", null, 10, true, false);
        SousCategorie28.setCategorieProduit(CategorieProduit7);
        p31.setSousCategorie(SousCategorie28);
        p31.setStatut(sproduit1);
        Produit p45 = new Produit("Bouchées crevettes grillées et fromage aux herbes", 4f, "45.jpg", null, 7, true, false);
        SousCategorie42.setCategorieProduit(CategorieProduit7);
        p45.setSousCategorie(SousCategorie42);
        p45.setStatut(sproduit1);
        Produit p51 = new Produit("Cake aux tomates séchées, feta et olives vertes", 8f, "51.jpg", null, 6, true, false);
        SousCategorie46.setCategorieProduit(CategorieProduit7);
        p51.setSousCategorie(SousCategorie46);
        p51.setStatut(sproduit1);
        Produit p55 = new Produit("Brochette de Camembert AOP de Normandie & Pont l'Evêque AOP de Normandie", 7f, "55.jpg", null, 12, true, false);
        SousCategorie49.setCategorieProduit(CategorieProduit7);
        p55.setSousCategorie(SousCategorie49);
        p55.setStatut(sproduit1);
        Produit p66 = new Produit("Boulettes de carottes au cumin, sésame et pavot", 7f, "66.jpg", null, 7, true, false);
        SousCategorie57.setCategorieProduit(CategorieProduit7);
        p66.setSousCategorie(SousCategorie57);
        p66.setStatut(sproduit1);
        Produit p70 = new Produit("Bruschetta aux asperges blanches et au jambon cru", 5f, "70.jpg", null, 8, true, false);
        SousCategorie3.setCategorieProduit(CategorieProduit7);
        p70.setSousCategorie(SousCategorie3);
        p70.setStatut(sproduit1);
        Produit p75 = new Produit("Sablé apéritif mimolette", 5f, "75.jpg", null, 11, true, false);
        SousCategorie64.setCategorieProduit(CategorieProduit7);
        p75.setSousCategorie(SousCategorie64);
        p75.setStatut(sproduit1);
        Produit p88 = new Produit("Roses de lasagnes chèvre épinard", 6f, "88.jpg", null, 12, true, false);
        SousCategorie74.setCategorieProduit(CategorieProduit7);
        p88.setSousCategorie(SousCategorie74);
        p88.setStatut(sproduit1);
        Produit p91 = new Produit("Gressins mikados salés de l'apéro", 6f, "91.jpg", null, 6, true, false);
        SousCategorie76.setCategorieProduit(CategorieProduit7);
        p91.setSousCategorie(SousCategorie76);
        p91.setStatut(sproduit1);
        Produit p96 = new Produit("Maple bacon pancake bite", 5f, "96.jpg", null, 6, true, false);
        SousCategorie80.setCategorieProduit(CategorieProduit7);
        p96.setSousCategorie(SousCategorie80);
        p96.setStatut(sproduit1);
        Produit p101 = new Produit("Camembert cocotte en nid de pizza", 6f, "101.jpg", null, 10, true, false);
        SousCategorie84.setCategorieProduit(CategorieProduit7);
        p101.setSousCategorie(SousCategorie84);
        p101.setStatut(sproduit1);
        Produit p111 = new Produit("Cannelés chorizo - chèvre", 8f, "111.jpg", null, 12, true, false);
        SousCategorie92.setCategorieProduit(CategorieProduit7);
        p111.setSousCategorie(SousCategorie92);
        p111.setStatut(sproduit1);
        Produit p116 = new Produit("Damier feuilleté de knacki", 4f, "116.jpg", null, 5, true, false);
        SousCategorie95.setCategorieProduit(CategorieProduit7);
        p116.setSousCategorie(SousCategorie95);
        p116.setStatut(sproduit1);
        Produit p131 = new Produit("Mystère chèvre carotte", 3f, "131.jpg", null, 5, true, false);
        SousCategorie107.setCategorieProduit(CategorieProduit7);
        p131.setSousCategorie(SousCategorie107);
        p131.setStatut(sproduit1);
        Produit p69 = new Produit("Barres chocolatées façon Lion", 8f, "69.jpg", null, 9, true, false);
        SousCategorie59.setCategorieProduit(CategorieProduit8);
        p69.setSousCategorie(SousCategorie59);
        p69.setStatut(sproduit1);
        Produit p114 = new Produit("Fudge blanc et noir (chocolat)", 6f, "114.jpg", null, 9, true, false);
        SousCategorie94.setCategorieProduit(CategorieProduit8);
        p114.setSousCategorie(SousCategorie94);
        p114.setStatut(sproduit1);

        p1.setTVA(TVA);
        p2.setTVA(TVA);
        p3.setTVA(TVA);
        p4.setTVA(TVA);
        p5.setTVA(TVA);
        p6.setTVA(TVA);
        p7.setTVA(TVA);
        p8.setTVA(TVA);
        p9.setTVA(TVA);
        p10.setTVA(TVA);
        p11.setTVA(TVA);
        p12.setTVA(TVA);
        p13.setTVA(TVA);
        p14.setTVA(TVA);
        p15.setTVA(TVA);
        p16.setTVA(TVA);
        p17.setTVA(TVA);
        p18.setTVA(TVA);
        p19.setTVA(TVA);
        p20.setTVA(TVA);
        p21.setTVA(TVA);
        p22.setTVA(TVA);
        p23.setTVA(TVA);
        p24.setTVA(TVA);
        p25.setTVA(TVA);
        p26.setTVA(TVA);
        p27.setTVA(TVA);
        p28.setTVA(TVA);
        p29.setTVA(TVA);
        p30.setTVA(TVA);
        p31.setTVA(TVA);
        p32.setTVA(TVA);
        p33.setTVA(TVA);
        p34.setTVA(TVA);
        p35.setTVA(TVA);
        p36.setTVA(TVA);
        p37.setTVA(TVA);
        p38.setTVA(TVA);
        p39.setTVA(TVA);
        p40.setTVA(TVA);
        p41.setTVA(TVA);
        p42.setTVA(TVA);
        p43.setTVA(TVA);
        p44.setTVA(TVA);
        p45.setTVA(TVA);
        p46.setTVA(TVA);
        p47.setTVA(TVA);
        p48.setTVA(TVA);
        p49.setTVA(TVA);
        p50.setTVA(TVA);
        p51.setTVA(TVA);
        p52.setTVA(TVA);
        p53.setTVA(TVA);
        p54.setTVA(TVA);
        p55.setTVA(TVA);
        p56.setTVA(TVA);
        p57.setTVA(TVA);
        p58.setTVA(TVA);
        p59.setTVA(TVA);
        p60.setTVA(TVA);
        p61.setTVA(TVA);
        p62.setTVA(TVA);
        p63.setTVA(TVA);
        p64.setTVA(TVA);
        p65.setTVA(TVA);
        p66.setTVA(TVA);
        p67.setTVA(TVA);
        p68.setTVA(TVA);
        p69.setTVA(TVA);
        p70.setTVA(TVA);
        p71.setTVA(TVA);
        p72.setTVA(TVA);
        p73.setTVA(TVA);
        p74.setTVA(TVA);
        p75.setTVA(TVA);
        p76.setTVA(TVA);
        p77.setTVA(TVA);
        p78.setTVA(TVA);
        p79.setTVA(TVA);
        p80.setTVA(TVA);
        p81.setTVA(TVA);
        p82.setTVA(TVA);
        p83.setTVA(TVA);
        p84.setTVA(TVA);
        p85.setTVA(TVA);
        p86.setTVA(TVA);
        p87.setTVA(TVA);
        p88.setTVA(TVA);
        p89.setTVA(TVA);
        p90.setTVA(TVA);
        p91.setTVA(TVA);
        p92.setTVA(TVA);
        p93.setTVA(TVA);
        p94.setTVA(TVA);
        p95.setTVA(TVA);
        p96.setTVA(TVA);
        p97.setTVA(TVA);
        p98.setTVA(TVA);
        p99.setTVA(TVA);
        p100.setTVA(TVA);
        p101.setTVA(TVA);
        p102.setTVA(TVA);
        p103.setTVA(TVA);
        p104.setTVA(TVA);
        p105.setTVA(TVA);
        p106.setTVA(TVA);
        p107.setTVA(TVA);
        p108.setTVA(TVA);
        p109.setTVA(TVA);
        p110.setTVA(TVA);
        p111.setTVA(TVA);
        p112.setTVA(TVA);
        p113.setTVA(TVA);
        p114.setTVA(TVA);
        p115.setTVA(TVA);
        p116.setTVA(TVA);
        p117.setTVA(TVA);
        p118.setTVA(TVA);
        p119.setTVA(TVA);
        p120.setTVA(TVA);
        p121.setTVA(TVA);
        p122.setTVA(TVA);
        p123.setTVA(TVA);
        p124.setTVA(TVA);
        p125.setTVA(TVA);
        p126.setTVA(TVA);
        p127.setTVA(TVA);
        p128.setTVA(TVA);
        p129.setTVA(TVA);
        p130.setTVA(TVA);
        p131.setTVA(TVA);
        p132.setTVA(TVA);
        p133.setTVA(TVA);
        p134.setTVA(TVA);
        p135.setTVA(TVA);
        p136.setTVA(TVA);
        p137.setTVA(TVA);
        p138.setTVA(TVA);
        p139.setTVA(TVA);
        p140.setTVA(TVA);
        p141.setTVA(TVA);
        p142.setTVA(TVA);
        p143.setTVA(TVA);
        p144.setTVA(TVA);
        p145.setTVA(TVA);
        p146.setTVA(TVA);
        p147.setTVA(TVA);
        p148.setTVA(TVA);
        p149.setTVA(TVA);
        p150.setTVA(TVA);

        em.persist(p1);
        em.persist(p2);
        em.persist(p3);
        em.persist(p4);
        em.persist(p5);
        em.persist(p6);
        em.persist(p7);
        em.persist(p8);
        em.persist(p9);
        em.persist(p10);
        em.persist(p11);
        em.persist(p12);
        em.persist(p13);
        em.persist(p14);
        em.persist(p15);
        em.persist(p16);
        em.persist(p17);
        em.persist(p18);
        em.persist(p19);
        em.persist(p20);
        em.persist(p21);
        em.persist(p22);
        em.persist(p23);
        em.persist(p24);
        em.persist(p25);
        em.persist(p26);
        em.persist(p27);
        em.persist(p28);
        em.persist(p29);
        em.persist(p30);
        em.persist(p31);
        em.persist(p32);
        em.persist(p33);
        em.persist(p34);
        em.persist(p35);
        em.persist(p36);
        em.persist(p37);
        em.persist(p38);
        em.persist(p39);
        em.persist(p40);
        em.persist(p41);
        em.persist(p42);
        em.persist(p43);
        em.persist(p44);
        em.persist(p45);
        em.persist(p46);
        em.persist(p47);
        em.persist(p48);
        em.persist(p49);
        em.persist(p50);
        em.persist(p51);
        em.persist(p52);
        em.persist(p53);
        em.persist(p54);
        em.persist(p55);
        em.persist(p56);
        em.persist(p57);
        em.persist(p58);
        em.persist(p59);
        em.persist(p60);
        em.persist(p61);
        em.persist(p62);
        em.persist(p63);
        em.persist(p64);
        em.persist(p65);
        em.persist(p66);
        em.persist(p67);
        em.persist(p68);
        em.persist(p69);
        em.persist(p70);
        em.persist(p71);
        em.persist(p72);
        em.persist(p73);
        em.persist(p74);
        em.persist(p75);
        em.persist(p76);
        em.persist(p77);
        em.persist(p78);
        em.persist(p79);
        em.persist(p80);
        em.persist(p81);
        em.persist(p82);
        em.persist(p83);
        em.persist(p84);
        em.persist(p85);
        em.persist(p86);
        em.persist(p87);
        em.persist(p88);
        em.persist(p89);
        em.persist(p90);
        em.persist(p91);
        em.persist(p92);
        em.persist(p93);
        em.persist(p94);
        em.persist(p95);
        em.persist(p96);
        em.persist(p97);
        em.persist(p98);
        em.persist(p99);
        em.persist(p100);
        em.persist(p101);
        em.persist(p102);
        em.persist(p103);
        em.persist(p104);
        em.persist(p105);
        em.persist(p106);
        em.persist(p107);
        em.persist(p108);
        em.persist(p109);
        em.persist(p110);
        em.persist(p111);
        em.persist(p112);
        em.persist(p113);
        em.persist(p114);
        em.persist(p115);
        em.persist(p116);
        em.persist(p117);
        em.persist(p118);
        em.persist(p119);
        em.persist(p120);
        em.persist(p121);
        em.persist(p122);
        em.persist(p123);
        em.persist(p124);
        em.persist(p125);
        em.persist(p126);
        em.persist(p127);
        em.persist(p128);
        em.persist(p129);
        em.persist(p130);
        em.persist(p131);
        em.persist(p132);
        em.persist(p133);
        em.persist(p134);
        em.persist(p135);
        em.persist(p136);
        em.persist(p137);
        em.persist(p138);
        em.persist(p139);
        em.persist(p140);
        em.persist(p141);
        em.persist(p142);
        em.persist(p143);
        em.persist(p144);
        em.persist(p145);
        em.persist(p146);
        em.persist(p147);
        em.persist(p148);
        em.persist(p149);
        em.persist(p150);

        // 7: CategorieMenu
//        CategorieMenu cm1 = new CategorieMenu(1, "Entrée");
//        CategorieMenu cm2 = new CategorieMenu(2, "Plat");
//        CategorieMenu cm3 = new CategorieMenu(3, "Dessert");

//        p1.setSousCategorie(SousCategorie1);
//        p2.setSousCategorie(SousCategorie1);
//        p3.setSousCategorie(SousCategorie1);
//        p4.setSousCategorie(SousCategorie1);
//        p5.setSousCategorie(SousCategorie2);
//        p6.setSousCategorie(SousCategorie2);
//        p7.setSousCategorie(SousCategorie2);
//        p8.setSousCategorie(SousCategorie3);
//        p9.setSousCategorie(SousCategorie3);
//        p10.setSousCategorie(SousCategorie3);
        // 8: Poste
        Poste poste1 = new Poste("cuisinier");
        Poste poste2 = new Poste("Serveur");

        Date d1 = new Date(20010101);
        // 9: Employe
        Employe emp1 = new Employe("Mr", "Talbo", "Julien", null, new Date(20170130));
        Employe emp2 = new Employe("Mr", "Vieira", "Alexanfre", null, new Date(20170130));
        Employe emp3 = new Employe("Mr", "Marc", "Landers", null, d1);
        Employe emp4 = new Employe("Mr", "Andre", "Chaussure", null, d1);
        Employe emp5 = new Employe("Mr", "Yves", "Laurent", null, d1);
        Employe emp6 = new Employe("Mr", "Nike", "Angel", null, d1);
        Employe emp7 = new Employe("Mr", "Dass", "Hasserl", null, d1);

        emp1.setPoste(poste1);
        emp2.setPoste(poste1);
        emp3.setPoste(poste2);
        emp4.setPoste(poste2);
        emp5.setPoste(poste2);
        emp6.setPoste(poste2);
        emp7.setPoste(poste2);

        // 10: Menu    
        Menu menu1 = new Menu("Menu simple", 15f);
        menu1.setTVA(TVA);
        menu1.setImage("simple.png");
        Menu menu2 = new Menu("Menu soft", 16f);
        menu2.setTVA(TVA);
        menu2.setImage("soft.png");
        Menu menu3 = new Menu("Menu Gourmand", 20f);
        menu3.setTVA(TVA);
        menu3.setImage("gourmand.png");

//        cm1.getProduits().add(p2);
//        cm1.getProduits().add(p3);
//        cm1.getProduits().add(p4);
//
//        cm2.getProduits().add(p5);
//        cm2.getProduits().add(p6);
//        cm2.getProduits().add(p7);
//
//        cm3.getProduits().add(p8);
//        cm3.getProduits().add(p9);
//        cm3.getProduits().add(p10);

        menu1.setEmploye(emp1);        
        menu2.setEmploye(emp1);        
        menu3.setEmploye(emp1);
        
        menu1.setStatut(smenu1);        
        menu2.setStatut(smenu1);        
        menu3.setStatut(smenu1);
        
        menu1.getProduits().add(p1);
        menu1.getProduits().add(p6);
        menu1.getProduits().add(p11);
        
        menu1.getProduits().add(p5);
        menu1.getProduits().add(p8);
        menu1.getProduits().add(p12);
        
        menu2.getProduits().add(p5);
        menu2.getProduits().add(p8);
        menu2.getProduits().add(p12);
        
        menu2.getProduits().add(p85);
        menu2.getProduits().add(p89);
        menu2.getProduits().add(p94);
        
        menu3.getProduits().add(p1);
        menu3.getProduits().add(p6);
        menu3.getProduits().add(p11);
        
        menu3.getProduits().add(p5);
        menu3.getProduits().add(p8);
        menu3.getProduits().add(p12);
        
        menu3.getProduits().add(p85);
        menu3.getProduits().add(p89);
        menu3.getProduits().add(p94);
        
        em.persist(menu1);
        em.persist(menu2);
        em.persist(menu3);
        
        // 11: Tabla
        Tabla table1 = new Tabla(1, 1, 2);
        Tabla table2 = new Tabla(2, 1, 2);
        Tabla table3 = new Tabla(3, 1, 2);
        Tabla table4 = new Tabla(4, 1, 4);
        Tabla table5 = new Tabla(5, 1, 4);
        Tabla table6 = new Tabla(6, 1, 4);
        Tabla table7 = new Tabla(7, 1, 4);
        Tabla table8 = new Tabla(8, 1, 4);
        Tabla table9 = new Tabla(9, 1, 4);
        Tabla table10 = new Tabla(10, 1, 6);
        Tabla table11 = new Tabla(11, 1, 6);
        Tabla table12 = new Tabla(12, 1, 6);
        Tabla table13 = new Tabla(13, 1, 8);
        Tabla table14 = new Tabla(14, 1, 8);
        Tabla table15 = new Tabla(15, 1, 8);
        Tabla table16 = new Tabla(16, 1, 12);
        Tabla table17 = new Tabla(17, 1, 12);
        Tabla table18 = new Tabla(18, 1, 12);

        // 12: Ligne Commande
        LigneCommande lc01 = new LigneCommande(false, p1, null, null);
        LigneCommande lc02 = new LigneCommande(false, p2, null, null);
        LigneCommande lc03 = new LigneCommande(true, p10, null, null);
        LigneCommande lc04 = new LigneCommande(false, p10, null, null);

        // 13: Commande
        Commande com01 = new Commande(new Date());
        Commande com02 = new Commande(new Date());

        lc01.setCommande(com01);
        lc02.setCommande(com01);
        com01.getLigneCommandes().add(lc01);
        com01.getLigneCommandes().add(lc02);
        com01.setTabla(table1);
        com02.setTabla(table1);
        lc04.setCommande(com02);
        com02.getLigneCommandes().add(lc04);

        Statut monStatus = new Statut(90, "confirmé");
        Statut serveurSt91 = new Statut(91, "validé");
        Statut serveurSt92 = new Statut(92, "en cours");
        Statut serveurSt93 = new Statut(93, "annulé");

        em.persist(monStatus);
        em.persist(serveurSt91);
        em.persist(serveurSt92);
        em.persist(serveurSt93);

        com02.setStatut(monStatus);
        System.out.println("mon status  : " + monStatus);

        em.persist(com01);
        em.persist(com02);
        em.persist(emp1);
        em.persist(emp2);

        em.persist(table1);
        em.persist(table2);
        em.persist(table3);
        em.persist(table4);
        em.persist(table5);
        em.persist(table6);
        em.persist(table7);
        em.persist(table8);
        em.persist(table9);
        em.persist(table10);
        em.persist(table11);
        em.persist(table12);
        em.persist(table13);
        em.persist(table14);
        em.persist(table15);
        em.persist(table16);
        em.persist(table17);
        em.persist(table18);

        em.persist(emp2);
        em.persist(emp3);
        em.persist(emp4);
        em.persist(emp5);
        em.persist(emp6);
        em.persist(emp7);

        // 14:
        TypeReglement typeReglement1 = new TypeReglement("CB");
        TypeReglement typeReglement2 = new TypeReglement("Espèce");
        TypeReglement typeReglement3 = new TypeReglement("Ticket Restaurant");
        TypeReglement typeReglement4 = new TypeReglement("Chèque");
        TypeReglement typeReglement5 = new TypeReglement("Nature");

        em.persist(typeReglement1);
        em.persist(typeReglement2);
        em.persist(typeReglement4);
        
        // 15:
        TypeCuisson typeCuisson1 = new TypeCuisson("Bleu");
        TypeCuisson typeCuisson2 = new TypeCuisson("Saignant");
        TypeCuisson typeCuisson3 = new TypeCuisson("A point");
        TypeCuisson typeCuisson4 = new TypeCuisson("Bien cuit");
        TypeCuisson typeCuisson5 = new TypeCuisson("Rosé");
        TypeCuisson typeCuisson6 = new TypeCuisson("Carbonisé");


    }
}
